DROP TABLE IF EXISTS `ad_element`;
CREATE TABLE `ad_element` (
  `ad_text` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '广告文字',
  `ad_name` varchar(255) COLLATE utf8_bin NOT NULL COMMENT '广告名称',
  `advertiser_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '广告商ID',
  `ad_combo_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '广告套餐ID',
   `ad_position_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '广告位置坐标ID(标清)',
   `ad_child_type_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '广告子类型ID',
   `ad_hd_position_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '广告位置坐标ID(高清)',
  `start_date` datetime  NOT NULL COMMENT '广告展示的开始时间',
  `end_date` datetime NOT NULL COMMENT '广告展示的结束时间',
  `ad_add_text` varchar(1000) COLLATE utf8_bin DEFAULT NULL COMMENT '附加文本信息',
  `ad_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '广告ID',
  `ad_flag` int(11) DEFAULT '0' COMMENT '广告是否包含附加信息的标志(0未附件数据 1纯文本 2网站链接)',
  `ad_status` int(11) DEFAULT '0' COMMENT '广告状态',
  `ad_format` int(11)  COMMENT '广告格式（1图片 2视频）',
  `ad_path` varchar(4000) COLLATE utf8_bin DEFAULT NULL COMMENT '文件路径',
  `ad_vedio_image_path` varchar(4000) COLLATE utf8_bin DEFAULT NULL COMMENT '视频截图文件路径',
  `id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '编号',
  `create_by` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `remarks` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `del_flag` char(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '删除标记',
  `play_end` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT'广告播放的开始时刻',
  `play_start` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '广告播放的结束时刻',
  PRIMARY KEY (`id`),
  KEY `ad_element_ad_id` (`ad_id`),
  KEY `ad_element_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='广告内容表';